spring:
  application:
    name: "dieta"
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/saludable-dieta?serverTimezone=UTC"
    username: "postgres"
    password: "postgres"
  flyway: true

server:
  port: 8080